options:
  logging: CLOUD_LOGGING_ONLY
  machineType: E2_HIGHCPU_8

substitutions:
  _REGION: northamerica-northeast1
  _REPOSITORY: coach-backend-repo
  _SERVICE: coach-backend
  # ⬇️ hardcode your project id here
  _IMAGE: northamerica-northeast1-docker.pkg.dev/gcp-class-16/coach-backend-repo/coach-backend

steps:
  - name: gcr.io/cloud-builders/mvn
    args: ["-B", "-f", "pom.xml", "clean", "package", "-DskipTests"]

  - name: gcr.io/cloud-builders/docker
    args: ["build", "-t", "${_IMAGE}:$SHORT_SHA", "."]

  - name: gcr.io/cloud-builders/docker
    args: ["push", "${_IMAGE}:$SHORT_SHA"]

  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      [
        "run","deploy","${_SERVICE}",
        "--image","${_IMAGE}:$SHORT_SHA",
        "--region","${_REGION}",
        "--platform","managed",
        "--allow-unauthenticated",
        "--port","8080"
      ]

images:
  - "${_IMAGE}:$SHORT_SHA"